import pickle

d = "./logs/qm9_default_2023_04_17__07_38_45/sample_2023_04_18__14_39_10/samples_0.pkl"
with open(d, "rb") as f:
    data = pickle.load(f)
print(len(data))
try:
    file = open('generate_data.txt', mode='a', encoding='utf-8')
except:
    print(f'open analyse file error!')
file.write(str(len(data)))
file.write('\n')
file.write(str(data[0]))
file.write('\n')
file.write(str(data[0].atom_type))
file.write('\n')
file.write(str(data[0].bond_edge_index))
file.write('\n')
file.write(str(data[0].edge_index))
file.write('\n')
file.write(str(data[0].edge_order))
file.write('\n')
file.write(str(data[0].edge_type))
file.write('\n')
file.write(str(data[0].idx))
file.write('\n')
file.write(str(data[0].is_bond))
file.write('\n')
file.write(str(data[0].num_nodes_per_graph))
file.write('\n')
file.write(str(data[0].num_pos_ref))
file.write('\n')
file.write(str(data[0].pos))
file.write('\n')
file.write(str(data[0].pos_gen))
file.write('\n')
file.write(str(data[0].pos_ref))
file.write('\n')
file.write(str(data[0].smiles))
file.write('\n')
file.close()